Add Support for Check Suites
PyGithub/PyGithub pull request #1646
Opened 2020-08-09 07:55 UTC by wrecker

NOTE: This PR includes changes from PR#1631

2020-08-09 08:11 UTC, wrecker commented
The failures for Python 3.6 doesn't seem to be related to my change.. am i missing something?

2020-08-09 09:05 UTC, s-t-e-v-e-n-k commented
It's lint again :-) I've merged your previous changes, please rebase.

2020-08-09 21:33 UTC, wrecker commented
@s-t-e-v-e-n-k .. I don't understand whats causing these lint errors. 
`github/Workflow.pyi:5: error: Module 'github.Commit' has no attribute 'Commit'; maybe "GitCommit"?
github/Tag.pyi:3: error: Module 'github.Commit' has no attribute 'Commit'; maybe "GitCommit"?
github/Repository.pyi:8: error: Module 'github.Commit' has no attribute 'Commit'; maybe "GitCommit"?
github/PullRequest.pyi:4: error: Module 'github.Commit' has no attribute 'Commit'; maybe "GitCommit"?
github/GithubObject.pyi:3: error: Module 'github.Commit' has no attribute 'Commit'; maybe "GitCommit"?
github/Comparison.pyi:3: error: Module 'github.Commit' has no attribute 'Commit'; maybe "GitCommit"?
github/Commit.pyi:4: error: Module 'github.Commit' has no attribute 'Commit'; maybe "GitCommit"?
github/Commit.pyi:15: error: Name 'Commit' already defined (possibly by an import)
github/Branch.pyi:4: error: Module 'github.Commit' has no attribute 'Commit'; maybe "GitCommit"?
github/MainClass.pyi:6: error: Module 'github.Commit' has no attribute 'Commit'; maybe "GitCommit"?`

2020-08-09 21:42 UTC, wrecker commented
Ignore my last comment. Fixed the lint errors. I also setup a python3.6 environment using docker. I can now run `tox` locally. So my next PR should be better :)

2020-08-28 04:22 UTC, s-t-e-v-e-n-k commented on github/Commit.pyi
> +    def get_comments(self) -> PaginatedList[CommitComment]: ...
This should probably be a separate change, but nice catch. :-)

2020-09-08 04:17 UTC, wrecker commented
Sorry for the long silence.. had to deal with production issues at work and then took a short break. Will start revisiting this and other PRs this week.

2020-10-06 15:01 UTC, hawkins commented
Very excited to see this, I would definitely use the checks api as soon as it ships. Any way I could lend a hand?

2020-10-21 15:46 UTC, dhruvmanila commented
I wanted the Check Run API endpoint for my side project so I created all the endpoints present in https://docs.github.com/en/free-pro-team@latest/rest/reference/checks#check-runs which includes:
- Creat a check run
- Get a check run
- Update a check run
- List check run annotations
- List check runs for Git reference

The "List check runs in a check suit" should be implement from the `check-suite` endpoint.

All the Python files, stub files, test files and replay data files have been written, I will create a PR in a few days as I am not in town currently. I have also separated them out in logical commits like single object files commit, single endpoint files commit, test files and replay data files.

2020-10-27 03:29 UTC, s-t-e-v-e-n-k requested changes
Sorry for taking so long, just two more nits and this can be merged.

2020-10-27 03:29 UTC, s-t-e-v-e-n-k commented on github/CheckSuite.py
> +        :rtype: string
Properties are 'type' not 'rtype'

2020-10-27 03:29 UTC, s-t-e-v-e-n-k commented on github/CheckSuite.py
> +        :rtype: bool
This actually calls a URL, so this needs more detail.

2020-11-11 11:49 UTC, sbesson commented
At [OME](github.com/ome), we are making extensive use of PyGithub  in our own [library](github.com/ome/scc/) to filter PRs opened against all our organizational repository and create daily integration branches. First and foremost, thanks for the continued support of this Python bridge.

As we are assessing the transition to GitHub Actions for CI/CD, we realized it make extensive use of the Checks API (as opposed to the Status API used by Travis CI/Circle CI) for reporting the outcome of its check runs and suites. In case it's useful, we performed some testing of this branch and were able to access check-suites and their metadata.

Looking forward to see this feature (and the related https://github.com/PyGithub/PyGithub/pull/1727 from @dhruvmanila) landing in a PyGitHub release. Let us know if we can help with the integration.

2020-11-30 03:52 UTC, s-t-e-v-e-n-k commented
@wrecker Thank you so much for your contribution, but I'm going to close this in favour of #1764, which incorporates your work.

2020-11-30 03:52 UTC, closed without merging