add transfer method
PyGithub/PyGithub pull request #1749
Opened 2020-11-10 02:53 UTC by tubaman

2020-11-10 03:50 UTC, s-t-e-v-e-n-k requested changes
I have some concerns about the code changes, but it's looking like a good first step. This also requires tests and the method signature added to Repository.pyi for type checking

2020-11-10 03:50 UTC, s-t-e-v-e-n-k commented on github/Repository.py
> +        :param new_owner: string
I mean, we could also have this accept an Organization, or a NamedUser ...

2020-11-10 03:50 UTC, s-t-e-v-e-n-k commented on github/Repository.py
> +        :param teams: list
A list of what?

2020-11-10 03:50 UTC, s-t-e-v-e-n-k commented on github/Repository.py
> +    def create_transfer_request(
This doesn't match the return type then? Either this creates a request to move the repository, which will happen at some point in the future, and the user then needs to go and use get_repo on the new name, or this should be called transfer and return the new repository object.

2020-11-20 22:10 UTC, tubaman commented
Agreed with all the comments above.  Unfortunately I don't have time to work this PR any further.  Just seemed like functionality and I wanted to [raise that issue](https://github.com/PyGithub/PyGithub/issues/1746) and perhaps give someone a head start with this PR

2022-04-16 09:39 UTC, closed without merging