add parent team id when calling create team function fix black precom…
PyGithub/PyGithub pull request #2278
Opened 2022-07-21 05:58 UTC by joosangkim

1. create team with `parent team id`
  * Based on github [official document](https://docs.github.com/en/rest/teams/teams#create-a-team) , creating team with a parent team id is supported but `PyGithub` doesn't support it yet. So I add this feature on  existing function named `create_team`. 

2. solve `pre-commit` dependency error 
* when run `pre-commit`, there are dependency issue on https://github.com/psf/black@20.8b1. `psf/black` has import issue with `click`. You can check the issue on this [issue page](https://github.com/psf/black/issues/2976)

2023-01-20 19:50 UTC, mitchLui commented
Is this still being worked on? I'd really appreciate it if this was available and can contribute if wanted.

2023-01-22 12:06 UTC, joosangkim commented
Hi @mitchLui I’ve forgot this PR because there are so many `parent_team_id` related PR. I’ll resolving my PR about conflicts and failed test.

2023-03-01 22:06 UTC, Cheshirez commented
Hi Is this PR still active?

2023-05-15 13:06 UTC, tobiasehlert commented
Hi @joosangkim, are you still working on this PR?
Would be really nice to get this implemented :)

2023-07-08 09:49 UTC, EnricoMi requested changes

2023-07-08 09:49 UTC, EnricoMi commented on github/Organization.py
>      def _useAttributes(self, attributes):
Attribute `parent_team_id` of `Organization` has to be set in `_useAttributes`

2023-07-08 09:49 UTC, EnricoMi commented on tests/Organization.py
> +            141496,
Can we assert the `parent_team_id` in `testAttributes`? I may have to record replay data for this.

2023-07-08 09:51 UTC, EnricoMi commented
> 2. solve `pre-commit` dependency error

@joosangkim Can we fix this in a separate PR? How come our CI does not break due to this error?

2023-12-19 09:09 UTC, EnricoMi commented
@joosangkim happy to merge once comments are addressed

2024-01-28 16:02 UTC, EnricoMi commented on github/Organization.py
>      def _useAttributes(self, attributes):
Btw., I can't see in the docs that Organization has a `parent_team_id` attribute...

2024-01-28 16:03 UTC, EnricoMi commented
Fixed by #2863.

2024-01-28 16:03 UTC, closed without merging