Add head_sha argument to Workflow.get_runs()
PyGithub/PyGithub pull request #2346
Opened 2022-10-31 15:28 UTC by thburghout

Adds missing head_sha argument to the query options of Workflow.get_runs().

First time contributing. Please let me know if something needs to be done differently. Some manual editing in the replay data was needed as `check.yml` does not exists anymore.

Solves #2337

2023-06-07 11:55 UTC, thburghout commented
Hi @JLLeitschuh, what would be the best way to move this forward? Can I update the pull request to get the review going?

2023-06-07 12:55 UTC, JLLeitschuh commented
> Can I update the pull request to get the review going?

That would be appropriate. The PR looks good to me, sans conflicts that need to be resolved.

2023-06-07 12:56 UTC, EnricoMi requested changes
While you are extending this method, can you also add the following missing parameters?
- created
- exclude_pull_requests
- check_suite_id

in the order listed at https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-workflow.

2023-06-07 12:56 UTC, EnricoMi commented on github/Workflow.py
>          :calls: `GET /repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs <https://docs.github.com/en/rest/reference/actions#workflow-runs>`_
Please update the docs link to https://docs.github.com/en/rest/actions/workflow-runs#list-workflow-runs-for-a-workflow

2023-06-07 12:56 UTC, EnricoMi commented
Please run `tox` locally and commit the changes.

2023-06-07 12:58 UTC, EnricoMi commented
Looks like `check_suite_id` has been added in master in the meanwhile.

2023-07-07 12:07 UTC, thburghout commented
@EnricoMi @JLLeitschuh this PR is be ready to be reviewed. If there is anything still needed, please let me know.

2023-07-07 13:09 UTC, EnricoMi approved these changes
LGTM!

2023-07-07 13:14 UTC, merged