merge WorkflowRun type stub back to source
PyGithub/PyGithub pull request #2554
Opened 2023-06-16 16:29 UTC by trim21

2023-06-23 07:06 UTC, EnricoMi requested changes
I like defining the attributes with their getter functions, but we should stick to one layout while migrating type stubs back: #2553

2023-06-25 06:11 UTC, trim21 commented
I found that instance attribute is not necessary

2023-06-26 06:27 UTC, EnricoMi approved these changes
LGTM, minor change requested.

2023-06-26 06:27 UTC, EnricoMi commented on github/WorkflowRun.py
>          """
You removed these docs from other methods, should remove here then as well.

2023-07-05 07:13 UTC, EnricoMi requested changes

2023-07-05 07:13 UTC, EnricoMi commented on github/WorkflowRun.py
>          return self._workflow_id.value
Sorry, but this property misses type annotation and lacks doc string removal.

2023-07-05 07:14 UTC, EnricoMi commented
Please request review when done, so this flags up as ready for me. Hard to keep track which PR is ready and which are in progress.

2023-07-05 07:17 UTC, trim21 commented
> Please request review when done, so this flags up as ready for me. Hard to keep track which PR is ready and which are in progress.

Sorry, I thought this PR is done when I trigger review request. Just didn't notice I missed one property.

2023-07-05 07:35 UTC, EnricoMi requested changes
Sorry, two more missing, please double-check as well.

2023-07-05 07:35 UTC, EnricoMi commented on github/WorkflowRun.py
>      def created_at(self):
missing typing

2023-07-05 07:35 UTC, EnricoMi commented on github/WorkflowRun.py
>      def updated_at(self):
missing typing

2023-07-05 07:41 UTC, trim21 commented
it's all typed this time!

2023-07-05 07:50 UTC, EnricoMi approved these changes
Looks like it is.

2023-07-05 07:50 UTC, merged