merge some simple class' type stubs back to source
PyGithub/PyGithub pull request #2570
Opened 2023-06-25 03:24 UTC by trim21

2023-06-26 06:52 UTC, EnricoMi requested changes
Types of attributes are not defined for many classes. Please turn this into a `Draft` until you are finished.

2023-06-26 06:52 UTC, EnricoMi commented on github/BranchProtection.py
>  class BranchProtection(github.GithubObject.CompletableGithubObject):
types of attributes are not defined for this class

2023-06-26 06:52 UTC, EnricoMi commented on github/CommitStats.py
>      """
types of attributes are not defined for this class

2023-06-26 06:52 UTC, EnricoMi commented on github/GitAuthor.py
>          return self.get__repr__({"name": self._name.value})
types of attributes are not defined for this class

2023-06-26 06:52 UTC, EnricoMi commented on github/GitBlob.py
types of attributes are not defined for this class

2023-06-26 06:52 UTC, EnricoMi commented on github/GitRef.py
types of attributes are not defined for this class

2023-06-26 06:54 UTC, trim21 commented
Types of attributes are not realy required in type system here...

2023-07-11 13:51 UTC, EnricoMi approved these changes
LGTM!

2023-07-11 13:57 UTC, merged