CI: update precommit & apply
PyGithub/PyGithub pull request #2600
Opened 2023-07-04 13:10 UTC by Borda

running `pre-cimmit autopudate` and apply new versions plus a few manual fixed asked by flake8

cc: @EnricoMi

2023-07-17 09:58 UTC, Borda commented
@sfdye @EnricoMi could you pls have look / review :flamingo:

2023-09-12 21:13 UTC, Borda commented
@EnricoMi mind have a look, pls :pray:

2023-09-26 19:28 UTC, Borda commented
@EnricoMi, how is it going? :chipmunk:

2023-11-14 18:31 UTC, Borda commented
@EnricoMi is there anything I can do to help it land? 🦩

2023-11-15 18:44 UTC, EnricoMi requested changes
Thanks for tidying this up, few minor comments.

2023-11-15 18:44 UTC, EnricoMi commented on .pre-commit-config.yaml
> +        args: [ "--fix=lf" ]
```suggestion
        args:
          - "--fix=lf"
```

2023-11-15 18:44 UTC, EnricoMi commented on .pre-commit-config.yaml
> +        args: [ "--py37-plus" ]
```suggestion
        args:
          - "--py37-plus"
```

2023-11-15 18:45 UTC, EnricoMi commented
Looks like there are some uncommitted changes: https://github.com/PyGithub/PyGithub/actions/runs/6867963961/job/18677425814?pr=2600#step:4:132

2023-11-15 20:44 UTC, Borda commented
> Looks like there are some uncommitted changes: [PyGithub/PyGithub/actions/runs/6867963961/job/18677425814?pr=2600#step:4:132](https://github.com/PyGithub/PyGithub/actions/runs/6867963961/job/18677425814?pr=2600#step:4:132)

yeah, this would be normally resolved wit the bot installed...
so let me run it locally and push update...

2023-11-19 16:53 UTC, EnricoMi approved these changes
LGTM!

2023-11-19 16:54 UTC, merged