Add SAML exception
PyGithub/PyGithub pull request #2613
Opened 2023-07-07 07:57 UTC by Borda

recently crossed this exception and think would be nice to catch it...

cc: @EnricoMi

2023-07-07 08:08 UTC, trim21 requested changes

2023-07-07 08:08 UTC, trim21 commented on github/Requester.py
> +            if "SAML enforcement" in message:
message is in lower case

2023-07-07 09:00 UTC, Borda commented on github/Requester.py
> +            if "SAML enforcement" in message:
```suggestion
            if "saml enforcement" in message.lower():
```

2023-07-07 11:32 UTC, trim21 commented on github/Requester.py
> +            if "saml enforcement" in message.lower():
message is already lower

2023-07-07 13:11 UTC, Borda commented on github/Requester.py
> +            if "saml enforcement" in message.lower():
```suggestion
            if "saml enforcement" in message:
```

2023-07-12 21:17 UTC, trim21 approved these changes
lgtm

2023-07-13 15:34 UTC, EnricoMi commented
Please request review so this flags up for me again.

2023-07-25 19:31 UTC, closed without merging