Add support for is_alphanumeric for autolinks
PyGithub/PyGithub pull request #2630
Opened 2023-07-14 19:53 UTC by janssonoskar

As a developer I'm currently unable to specify whether I want to use alphanumeric (default) or numeric matching for autolink.

I added an bool attribute "is_alphanumerical" to Autolink and a parameter to "create_autolink" in Repository.

2023-07-15 06:05 UTC, trim21 requested changes

2023-07-15 06:05 UTC, trim21 commented on github/Repository.py
> +    def create_autolink(self, key_prefix, url_template, is_alphanumeric=True):
please use `NotSet` as default value

2023-07-21 23:44 UTC, janssonoskar commented on github/Repository.py
> +    def create_autolink(self, key_prefix, url_template, is_alphanumeric=True):
Fixed

2023-08-15 21:34 UTC, janssonoskar commented
@EnricoMi Hi, I haven't got authentication to work to record tests, is that something you could help me with?

2023-08-31 18:30 UTC, EnricoMi approved these changes
LGTM!

2023-08-31 19:08 UTC, merged