Merge `Gist` type stub back to source
PyGithub/PyGithub pull request #2655
Opened 2023-07-18 17:31 UTC by trim21

2023-07-18 17:45 UTC, trim21 commented on github/Gist.py
> +        assert (not is_defined(files)) or all(
`is_undefined` here can't narrow `files` to `dict`, so  we have to use `not isdefined(files)` or `isinstance(files, _NotSetType)`

2023-08-18 05:47 UTC, EnricoMi requested changes
minor cleanups

2023-08-18 05:47 UTC, EnricoMi commented on github/Gist.py
> +    def fork_of(self) -> github.Gist.Gist:
```suggestion
    def fork_of(self) -> Gist:
```

2023-08-18 05:47 UTC, EnricoMi commented on github/Gist.py
> +    def owner(self) -> github.NamedUser.NamedUser:
```suggestion
    def owner(self) -> NamedUser:
```

2023-08-18 05:47 UTC, EnricoMi commented on github/Gist.py
> +    def user(self) -> github.NamedUser.NamedUser:
```suggestion
    def user(self) -> NamedUser:
```

2023-08-30 06:03 UTC, EnricoMi commented
@trim21 what do you think about my comments above? I'd like to continue merging these PRs and this affects many of your PRs.

2023-08-30 06:08 UTC, trim21 commented
> @trim21 what do you think about my comments above? I'd like to continue merging these PRs and this affects many of your PRs.

see https://github.com/PyGithub/PyGithub/pull/2727#issuecomment-1684146096

2023-08-30 07:07 UTC, EnricoMi approved these changes
LGTM!

2023-08-30 07:08 UTC, merged