Merge `GistComment` type stub back to source
PyGithub/PyGithub pull request #2657
Opened 2023-07-18 18:02 UTC by trim21

2023-07-20 18:24 UTC, Borda approved these changes

2023-08-18 05:48 UTC, EnricoMi requested changes
minor cleanups

2023-08-18 05:48 UTC, EnricoMi commented on github/GistComment.py
> +    def user(self) -> github.NamedUser.NamedUser:
```suggestion
    def user(self) -> NamedUser:
```

2023-08-18 05:48 UTC, EnricoMi commented on github/GistComment.py
> +        self._user: Attribute[github.NamedUser.NamedUser] = NotSet
```suggestion
        self._user: Attribute[NamedUser] = NotSet
```

2023-08-18 16:28 UTC, trim21 commented on github/GistComment.py
> +    def user(self) -> github.NamedUser.NamedUser:
I would suggest no.

let's discuss https://github.com/PyGithub/PyGithub/pull/2727 first.

2023-08-30 07:08 UTC, EnricoMi approved these changes
LGTM!

2023-08-30 07:12 UTC, merged