manage require_last_push_approval branch protection
PyGithub/PyGithub pull request #2716
Opened 2023-08-12 00:47 UTC by terenho

fixes #2360

2023-08-21 08:09 UTC, EnricoMi requested changes
Can we have tests for the new fields?

2023-08-24 07:33 UTC, terenho commented on github/Branch.py
>      ) -> None:
Added `allow_deletions` in the latest commits

2023-08-24 07:33 UTC, terenho commented on github/BranchProtection.py
Added `allow_deletions` in the latest commits

2023-08-24 07:34 UTC, terenho commented
> Can we have tests for the new fields?

Added/updated tests for the new fields in the latest commits

2023-10-13 08:32 UTC, terenho commented
@EnricoMi I have added the allow_deletion function and added tests, I also resolved a merge conflict. This PR is ready for review.

2024-01-23 19:28 UTC, EnricoMi commented
Superseded by #2873, added you as co-author to appreciate your contribution.

2024-01-23 19:28 UTC, closed without merging