feat: add ``visibility`` in ``Repository.edit()``
PyGithub/PyGithub pull request #2742
Opened 2023-08-31 16:01 UTC by RobPasMue

According to https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#update-a-repository

``visibility`` is a new parameter accepted. This PR exposes this argument.

2023-08-31 16:19 UTC, RobPasMue commented
Hi @trim21 ! Let me know if I need to do anything else to get this feature merged :) I hope I did things properly

2023-08-31 17:55 UTC, EnricoMi requested changes
While you are adding a missing attribute, can you add those that are also missing, e.g.
- is_template
- use_squash_pr_title_as_default
- squash_merge_commit_title
- squash_merge_commit_message
- merge_commit_title
- merge_commit_message
- web_commit_signoff_required

Please check if I missed some.

2023-08-31 17:55 UTC, EnricoMi commented on github/Repository.py
> +        assert visibility is github.GithubObject.NotSet or isinstance(visibility, str), visibility
Can we assert here `visibility` has only the allowed values?
```suggestion
        assert visibility is github.GithubObject.NotSet or visibility in [
            "public", "private"
        ], visibility
```

2023-09-01 06:02 UTC, RobPasMue commented
Yep, for sure @EnricoMi - let me do that! =)

2023-09-01 08:15 UTC, EnricoMi requested changes
Can we get add all those new attributes to `_initAttributes` and `_useAttributes` and create getters as well? Please record test data for `testAttributes` and add those attributes there as well.

2023-09-01 08:15 UTC, EnricoMi commented on tests/Repository.py
>              has_issues=True,
Can we test will all new arguments? Recording test data should be easy to do.

2023-09-01 11:39 UTC, RobPasMue commented
Hi @EnricoMi - issues addressed. I added the properties, initialized the attributes and modified the useAttributes function. I also updated the test data. I hope everything is fine now. Let me know if you need anything else

2023-09-01 17:13 UTC, MaxJPRey commented
Nice work @RobPasMue . Thanks for updating the properties according to the API.

2023-09-04 07:26 UTC, EnricoMi approved these changes
Awesome, good work!

2023-09-04 07:28 UTC, merged