Merge `github/Organization.pyi` back to source
PyGithub/PyGithub pull request #2744
Opened 2023-09-01 12:54 UTC by trim21

2023-09-04 08:51 UTC, EnricoMi requested changes

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
> +        assert role is NotSet or isinstance(role, str), role
```suggestion
        assert is_optional(role, str), role
```

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
> +        if role is not NotSet:
```suggestion
        if is_defined(role):
```

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
> +        assert private is NotSet or isinstance(private, bool), private
```suggestion
        assert is_optional(description, str), description
        assert is_optional(private, bool), private
```

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
>              post_parameters["active"] = active
This should use `NotSet.remove_unset_items`.

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
> +        assert allow_update_branch is NotSet or isinstance(allow_update_branch, bool), allow_update_branch
they all can use `is_optional`

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
> +            assert selected_repositories is NotSet
```suggestion
            assert is_undefined(selected_repositories)
```

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
> +        assert description is NotSet or isinstance(description, str), description
```suggestion
        assert is_optional(permission, str), permission
        assert is_optional(privacy, str), privacy
        assert is_optional(description, str), description
```

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
>              post_parameters["description"] = description
should use `NotSet.remove_unset_items`

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
> +            assert selected_repositories is NotSet
```suggestion
            assert is_undefined(selected_repositories)
```

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
>          post_parameters = dict()
should use `NotSet.remove_unset_items`

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
> +        assert name is NotSet or isinstance(name, str), name
```suggestion
        assert is_optional(billing_email, str), billing_email
        assert is_optional(blog, str), blog
        assert is_optional(company, str), company
        assert is_optional(description, str), description
        assert is_optional(email, str), email
        assert is_optional(location, str), location
        assert is_optional(name, str), name
```

2023-09-04 08:51 UTC, EnricoMi commented on github/Organization.py
> +        assert active is NotSet or isinstance(active, bool), active
```suggestion
        assert is_optional(active, bool), active
```

2023-09-04 13:21 UTC, trim21 commented
this is strange, I didn't touch any test files but tests are broken

2023-09-07 06:40 UTC, EnricoMi commented on github/Organization.py
> +        assert is_undefined(email) ^ is_undefined(user), "specify only one of email or user"
Operator `!=` might be more readable
```suggestion
        assert is_defined(email) != is_defined(user), "specify only one of email or user"
```

2023-09-07 06:40 UTC, EnricoMi commented on github/Organization.py
> +        post_parameters: dict[str, Any] = {
why not having `NotSet.remove_unset_items` with `events` and `active` combined into this dict declaration?

2023-09-07 06:40 UTC, EnricoMi commented on github/Organization.py
> +        post_parameters: dict[str, Any] = {
Why not using `NotSet.remove_unset_items` here?

2023-09-07 08:38 UTC, EnricoMi commented on github/Organization.py
>          put_parameters = {}
candidate for `NotSet.remove_unset_items`

2023-09-07 08:41 UTC, EnricoMi commented on github/Organization.py
> +        url_parameters: dict[str, Any] = {}
candidate for `NotSet.remove_unset_items`

2023-09-07 08:41 UTC, EnricoMi commented on github/Organization.py
>          url_parameters = dict()
candidate for `NotSet.remove_unset_items`

2023-09-07 08:41 UTC, EnricoMi commented on github/Organization.py
>          url_parameters = {}
candidate for `NotSet.remove_unset_items`

2023-09-07 08:44 UTC, EnricoMi commented on github/Organization.py
>          post_parameters = {"repositories": repos}
Why not merging the `update` from below into this?
```suggestion
        post_parameters = NotSet.remove_unset_items(
                {
                    "repositories": repos,
                    "lock_repositories": lock_repositories,
                    "exclude_attachments": exclude_attachments,
                }
            )
```

2023-09-12 10:10 UTC, EnricoMi approved these changes
LGTM!

2023-09-12 10:10 UTC, merged