Add state and submitted_at attributes to TimelineEvent
PyGithub/PyGithub pull request #2757
Opened 2023-09-13 14:02 UTC by mohamed-haidara-cko

This PR add two new attributes for event type `reviewed`:

- `state`: The state of the submitted review. Can be one of: `commented`, `changes_requested`, `approved` or `dismissed`.
- `submitted_at`: `The timestamp indicating when the review was submitted.`

Doc: https://docs.github.com/en/rest/overview/issue-event-types?apiVersion=2022-11-28#properties-for-reviewed

2023-09-14 19:32 UTC, EnricoMi requested changes
I am wondering if it is worth adding and maintaining all those attributes of all those event types... Any idea how this could be done with minimal effort?

2023-09-15 08:17 UTC, mohamed-haidara-cko commented on github/TimelineEvent.py
> +            ]
I used the script `scripts/add_attribute.py` to add the attributes.

2023-09-15 08:56 UTC, mohamed-haidara-cko commented
> I am wondering if it is worth adding and maintaining all those attributes of all those event types... Any idea how this could be done with minimal effort?

We can leverage the OpenAPI Spec, which seems to be up to date: https://github.com/github/rest-api-description, and generate the code from that.

 I don't know if you considered that in the past but it could widely reduce the maintenance burden given the size of GitHub REST API

2023-10-17 07:21 UTC, trim21 commented on github/TimelineEvent.py
> +        if is_defined(self._body):
I think we don't need to check if it's defined, `NotSet` itself is already `Attribute[None]`, you can just return its `.value`.

2025-02-13 09:01 UTC, closed without merging