Cast last_modified as a date
PyGithub/PyGithub pull request #2772
Opened 2023-09-29 16:23 UTC by chouetz

Nearly all dates are returned as `datetime.datetime`
I don't know if all the date format retrieved from headers are consistent, but if it's the case we could get last_modified directly as a datetime like others in the module

2023-10-03 15:56 UTC, EnricoMi commented
This would be a breaking change, and `last_modified` could rightly be considered a header attribute of type string,

I'd prefer to introduce a separate property `last_modified_datetime: Optional[datetime]`. Using `_makeDatetimeAttribute` would also help to support more than just a single hard-coded format.

2023-10-04 15:42 UTC, chouetz commented
> This would be a breaking change, and `last_modified` could rightly be considered a header attribute of type string,
> 
> I'd prefer to introduce a separate property `last_modified_datetime: Optional[datetime]`. Using `_makeDatetimeAttribute` would also help to support more than just a single hard-coded format.
> 
> And here should be some asserts on this property in tests.

Many thanks for your comment, I'll update the PR this way and let you know when it's ready

2023-10-10 07:18 UTC, chouetz commented
Probably needs #2783 for the failing job, @EnricoMi can you check the PR content again please?
Many thanks in advance

2023-10-10 11:08 UTC, EnricoMi requested changes

2023-10-10 11:08 UTC, EnricoMi commented on github/GithubObject.py
> +        return self._makeDatetimeAttribute(self._headers.get(Consts.RES_LAST_MODIFIED))  # type: ignore
We can simplify this to
```suggestion
        return self._makeDatetimeAttribute(self.last_modified)  # type: ignore
```

2023-10-10 11:08 UTC, EnricoMi commented on github/GithubObject.py
> +        return self._makeDatetimeAttribute(self._headers.get(Consts.RES_LAST_MODIFIED))  # type: ignore
Method `self._makeDatetimeAttribute` returns an `Attribute`, but we want to return the value, so we need to
```suggestion
        return self._makeDatetimeAttribute(self._headers.get(Consts.RES_LAST_MODIFIED)).value  # type: ignore
```

2023-10-10 11:44 UTC, chouetz commented on github/GithubObject.py
> +        return self._makeDatetimeAttribute(self.last_modified)  # type: ignore
```suggestion
        return self._makeDatetimeAttribute(self.last_modified).value  # type: ignore
```

2023-10-10 11:50 UTC, chouetz commented
Thanks for your time @EnricoMi

2023-10-18 13:41 UTC, chouetz commented
OK for review @EnricoMi, many thanks in advance

2023-11-26 20:42 UTC, EnricoMi approved these changes
LGTM!

2023-11-26 20:44 UTC, merged