github/GitRelease.py added "make_latest" option for def "update_release"
PyGithub/PyGithub pull request #2788
Opened 2023-10-11 04:07 UTC by fb929

1. The problem:
def "update_release" can not make release as "latest"

2. How solving the problem:
adding optional parameter "make_latest", from original api doc: https://docs.github.com/en/free-pro-team@latest/rest/releases/releases?apiVersion=2022-11-28#update-a-release--code-samples

2023-10-21 16:17 UTC, trim21 commented
can you also update document link in docstring? current link is out of data.

2023-12-20 15:54 UTC, pfarrell commented
@fb929 I was just about to submit a PR to do exactly this.  
Are you planning to complete this PR?  This is a very feature I needed and had to implement by calling the github rest api directly.  I'd much prefer to have support in PyGithub.

2023-12-22 14:33 UTC, EnricoMi requested changes
While you are here, can you please add `discussion_category_name` as well?

2023-12-22 14:33 UTC, EnricoMi commented on github/GitRelease.py
> +            assert isinstance(make_latest, bool), make_latest
documentation says, this is a string
```suggestion
            assert make_latest in ["true", "false", "legacy"], make_latest
```

2023-12-22 14:35 UTC, EnricoMi commented
@pfarrell feel free to fork @fb929's repo and branch and create a new PR to finish this. This way, @fb929's contribution is credited and we get this over the finish line.

2023-12-22 14:35 UTC, EnricoMi commented
Looks like `message` has been renamed to `body`. This should be reflected in another PR to avoid this to break in the future. https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28

2024-01-28 15:52 UTC, EnricoMi commented on github/GitRelease.py
> +        make_latest: Opt[bool] = NotSet,
Adding this here may break user code, can you add this at the end of the argument list?

2024-01-28 15:53 UTC, EnricoMi commented
@pfarrell @fb929 can we get this over the finish line?

2024-01-30 21:30 UTC, treee111 commented
I tackled the PR review of this PR in the linked PR. @trim21 and @EnricoMi feel free to review.

> Looks like `message` has been renamed to `body`. This should be reflected in another PR to prevent this from breaking in the future. https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28

we already send/post that as `body` to the Github API and have `message` only as input to PyGithub if I am correct? So no need for adjustment (because that would break user code). See:
https://github.com/PyGithub/PyGithub/blob/7e7653fb7cb054d3b03dd5f89dea1a2a79350827/github/GitRelease.py#L204-L210

2024-02-03 17:19 UTC, pfarrell commented
> @pfarrell @fb929 can we get this over the finish line?

@EnricoMi, apologies for missing the alerts on this, thanks @@treee111 for picking this up

2024-02-03 18:44 UTC, treee111 commented
You are welcome @pfarrell. Feel free to test the coding and comment if it worked for you! Helps the PR getting merged :-)

2024-02-04 19:19 UTC, EnricoMi commented
Closed in favour of #2888.

2024-02-04 19:19 UTC, closed without merging