use new type assert functions in Repository.py
PyGithub/PyGithub pull request #2798
Opened 2023-10-17 06:57 UTC by trim21

2023-12-09 16:04 UTC, trim21 commented
@EnricoMi

2023-12-10 13:55 UTC, EnricoMi requested changes
Looks good, some minor adjustments.

2023-12-10 13:55 UTC, EnricoMi commented on github/Repository.py
> +        assert is_undefined(per) or per in ("day", "week"), "per must be day or week, day by default"
```suggestion
        assert per in ["day", "week", NotSet], "per must be day or week, day by default"
```

2023-12-10 13:55 UTC, EnricoMi commented on github/Repository.py
> +        assert is_undefined(per) or per in ("day", "week"), "per must be day or week, day by default"
```suggestion
        assert per in ["day", "week", NotSet], "per must be day or week, day by default"
```

2023-12-10 13:55 UTC, EnricoMi commented on github/Repository.py
> +            is_undefined(milestone) or milestone in ("*", "none") or isinstance(milestone, github.Milestone.Milestone)
```suggestion
            milestone in ["*", "none", NotSet] or isinstance(milestone, github.Milestone.Milestone)
```

2023-12-19 08:56 UTC, EnricoMi approved these changes
LGTM!

2023-12-19 09:02 UTC, merged