Update the class name for NetrcAuth in the examples
PyGithub/PyGithub pull request #2860
Opened 2023-12-13 00:38 UTC by vinnybod

The examples state that to use netrc auth, the class `Auth.Netrc` should be used. But it is actually `Auth.NetrcAuth`.

The release notes for 2.1.0 are also wrong, but I wasn't sure if that should be immutable.

2023-12-13 06:18 UTC, EnricoMi commented
Good catch, please update the changelog as well.

2023-12-18 16:52 UTC, vinnybod commented
@EnricoMi updated changes.rst

2023-12-19 08:32 UTC, EnricoMi requested changes

2023-12-19 08:32 UTC, EnricoMi commented on doc/changes.rst
> +    >>> auth = Auth.NetrcAuth()
There is another occurrence in line 113.

2023-12-22 14:26 UTC, EnricoMi approved these changes
LGTM!

2023-12-22 14:36 UTC, merged

2023-12-22 14:36 UTC, EnricoMi commented
Thanks!