name and message are not required when generate_release_notes it true
PyGithub/PyGithub pull request #2868
Opened 2024-01-05 13:28 UTC by heitorpolidoro

Name and Message are not required when generate_release_notes it true in the API:[ name and message are not required when generate_release_notes it true](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#create-a-release)

Broke if you want to use generate_release_notes without passing name or message to generate automatically

2024-01-26 15:46 UTC, EnricoMi commented on github/Repository.py
> +        release_name: Opt[str] = NotSet,
This is a breaking change, but I cannot see how to avoid that...

2024-01-26 15:46 UTC, EnricoMi commented on github/Repository.py
> +        release_name: Opt[str] = NotSet,
Please adjust the order of the `:param`s in the docstring.

2024-01-26 15:46 UTC, EnricoMi commented on github/Repository.py
> +        assert is_optional(name, str), name
Should we consider the value of `generate_release_notes`? As you said, it is optional only if `generate_release_notes` is true.

2024-02-21 08:18 UTC, EnricoMi commented on github/Repository.py
>          assert isinstance(generate_release_notes, bool), generate_release_notes
I think if we swap the `or` elemens, this reads more clearly:
```suggestion
        assert isinstance(generate_release_notes, bool), generate_release_notes
        assert isinstance(name, str) or generate_release_notes and is_optional(name, str), name
        assert isinstance(message, str) or generate_release_notes and is_optional(message, str), message
        assert isinstance(draft, bool), draft
        assert isinstance(prerelease, bool), prerelease
```
And we need to assert `generate_release_notes` before using it as a `bool`.

2024-02-21 08:23 UTC, EnricoMi commented on github/Repository.py
> +        release_name: Opt[str] = NotSet,
I am afraid we have to revert this breaking change. Please replace
```
        release_name: str,
        release_message: str,
```
with
```
        release_name: Opt[str],
        release_message: Opt[str],
```
instead.

Calling code will have to explicitly provide `release_name=None, release_message=None`.

2024-02-22 19:05 UTC, EnricoMi requested changes
Happy to approve, please see
- https://github.com/PyGithub/PyGithub/pull/2868/files#r1497080554
- https://github.com/PyGithub/PyGithub/pull/2868/files#r1497083233

2024-02-26 23:07 UTC, heitorpolidoro commented
Sorry for the delay in fixing

2024-03-02 11:38 UTC, EnricoMi requested changes
Does this work for you?

2024-03-02 11:38 UTC, EnricoMi commented on github/Repository.py
> +        ), message
This project doesn't use `None` for unset optional arguments but `NotSet`. Staying with the convention:
```suggestion
        assert isinstance(name, str) or generate_release_notes and is_optional(name, str), name
        assert (
            isinstance(message, str) or generate_release_notes and is_optional(message, str)
        ), message
```

2024-03-21 11:03 UTC, merged