Add runner attributes to WorkflowJob
PyGithub/PyGithub pull request #2902
Opened 2024-02-17 22:41 UTC by boomanaiden154

This patch adds the runner attributes to the WorkflowJob class. The four attributes, runner_id, runner_name, runner_group_id, and runner_group_name are always sent along with the job information, but before this patch, are not represented in PyGtithub. This patch adds the attributes and test coverage.

2024-02-22 19:52 UTC, EnricoMi requested changes
This looks good. While you are there, could you add the remaining missing attributes?
- created_at
- head_branch
- labels
- run_attempt
- started_at
- status
- steps
- url
- workflow_name

2024-03-14 18:21 UTC, EnricoMi requested changes
While you are adding new attributes, can you please add all missing attributes? I think these are also missing:
- run_attempt
- created_at
- completed_at
- labels
- workflow_name
- head_branch

2024-03-14 18:21 UTC, EnricoMi commented on github/WorkflowJob.py
> +        self._runner_group_name: Attribute[str] = NotSet
Can you keep this list of attributes in alphabetical order?

2024-03-16 05:32 UTC, xvega commented
> Looks like I did this review before... what a pity...

To speed things up, I opened a PR https://github.com/PyGithub/PyGithub/pull/2921 with @boomanaiden154 changes and addressed your feedback @EnricoMi

2024-03-21 10:45 UTC, EnricoMi commented
Superseded by #2921.

2024-03-21 10:45 UTC, closed without merging