Commit verification support
PyGithub/PyGithub pull request #3028
Opened 2024-08-28 07:43 UTC by timgates42

Add support for verification component of Commit API response to see if commit has been signed and the signature has been checked by Github

2024-10-27 17:12 UTC, EnricoMi requested changes
This looks great, thanks for the contribution! Can you a test asserting `commit.verification` for a commit that has `CommitVerification` attributes set?

2024-10-30 23:56 UTC, timgates42 commented
Thanks @EnricoMi have added

2025-02-15 00:30 UTC, timgates42 commented
@EnricoMi let me know if anything more required - Thanks!

2025-02-15 00:35 UTC, timgates42 commented
this was added it appears also via https://github.com/PyGithub/PyGithub/commit/6276e20f27da94d3fcef8e6b2635097320cac782 which is now merged so will close this pr

2025-02-15 11:07 UTC, EnricoMi commented
It is always better to have proper objects than dicts. I have also added `verified_at`.

2025-02-15 11:17 UTC, EnricoMi commented
Renamed to `GitCommitVerification`.

2025-02-15 17:06 UTC, EnricoMi approved these changes
LGTM!

2025-02-15 17:09 UTC, merged