Adding very basic support for GitHub packages
PyGithub/PyGithub pull request #3074
Opened 2024-10-30 20:56 UTC by Henkhogan

I found that there is no feature available to query packages like docker images thus I tried to add the ability to query them using the same code patterns that I found in the repo.

This PR only covers a small fraction of the Package APIs: https://docs.github.com/en/rest/packages/packages?apiVersion=2022-11-28

2024-12-21 02:11 UTC, GTWALOM approved these changes

2024-12-21 02:15 UTC, GTWALOM commented
I was hoping this functionality was already in the library.
I really would like to have this asap.
Somebody please have the official reviewer check this.

2025-02-03 18:12 UTC, EnricoMi requested changes
Solid start, please add to `Organization` as well (#3184).

2025-02-03 18:12 UTC, EnricoMi commented on github/PackageVersion.py
> +        self._updated_at: Opt[str] = NotSet
I think these attribites can be of type datetime.

2025-02-03 18:12 UTC, EnricoMi commented on mytest.py
> +from github import Github
I think, this is not meant to go into the PR.

2025-02-03 18:12 UTC, EnricoMi commented on tests/Package.py
> +class Repository(Framework.TestCase):
```suggestion
class Package(Framework.TestCase):
```

2025-02-03 18:12 UTC, EnricoMi commented on github/AuthenticatedUser.py
> +        return github.Package.Package(self._requester, headers, data, completed=True)
```suggestion
        url = f"{self.url}/packages/{package_type.value}/{package_name}"
        return github.Package.Package(self._requester, url=url)
```

2025-02-03 18:12 UTC, EnricoMi commented on github/AuthenticatedUser.py
> +    def get_packages(self, package_type: github.Package.PackageType) -> PaginatedList[Package]:
Please add parameter `visibility` here.

2025-02-03 18:12 UTC, EnricoMi commented on github/Package.py
> +        self._updated_at: Attribute[str] = NotSet
Please use `datetime` here.

2025-04-03 15:55 UTC, Prateikx commented on github/AuthenticatedUser.py
> +        assert isinstance(package_type , github.Package.PackageType), package_type
**✨ AI Suggestion:** The package_type parameter should be validated as a member of the PackageType enum to prevent unexpected behavior.
```suggestion
        if not isinstance(package_type, github.Package.PackageType):
            raise TypeError("package_type must be a member of github.Package.PackageType enum")
        assert isinstance(package_name, str), package_name
```

2025-04-03 15:55 UTC, Prateikx commented on github/NamedUser.py
> +    def get_package(self) -> Package:
**✨ AI Suggestion:** The `get_package` method lacks parameters for package_type and package_name, making it impossible to specify which package to retrieve.
```suggestion
    def get_package(self, package_type: github.Package.PackageType, package_name: str) -> Package:
        """
        :calls: `GET /users/{user}/packages/{package_type}/{package_name} <https://docs.github.com/en/rest/reference/packages>`_
        """
        if not isinstance(package_type, github.Package.PackageType):
            raise TypeError("package_type must be a member of github.Package.PackageType enum")
        assert isinstance(package_name, str), package_name
        headers, data = self._requester.requestJsonAndCheck("GET", f"{self.url}/packages/{package_type.value}/{package_name}")
        return github.Package.Package(self._requester, headers, data, completed=True)
```

2025-04-03 15:55 UTC, Prateikx commented on tests/Package.py
> +        self.packages = self.user.get_packages("astral-sh")
**✨ AI Suggestion:** The get_packages method requires a PackageType enum value, not a string.  This will cause a TypeError.
```suggestion
        self.packages = self.user.get_packages(PackageType.CONTAINER)
```

2025-04-03 16:07 UTC, Prateikx commented on github/AuthenticatedUser.py
> +        assert isinstance(package_type , github.Package.PackageType), package_type
**✨ AI Suggestion:** The `package_type` parameter should be validated as a member of the `PackageType` enum, not just its type.
```suggestion
        if not isinstance(package_type, github.Package.PackageType):
            raise TypeError("package_type must be an instance of github.Package.PackageType")
        if not isinstance(package_name, str):
            raise TypeError("package_name must be a string")
```

2025-04-03 16:07 UTC, Prateikx commented on github/NamedUser.py
> +    def get_package(self) -> Package:
**✨ AI Suggestion:** The `get_package` method lacks parameters for package type and name, making it unusable for retrieving specific packages.
```suggestion
    def get_package(self, package_type: github.Package.PackageType, package_name: str) -> Package:
        """
        :calls: `GET /user/packages/PACKAGE_TYPE/PACKAGE_NAME <https://docs.github.com/en/rest/reference/packages>`_
        """
        if not isinstance(package_type, github.Package.PackageType):
            raise TypeError("package_type must be an instance of github.Package.PackageType")
        if not isinstance(package_name, str):
            raise TypeError("package_name must be a string")
        headers, data = self._requester.requestJsonAndCheck("GET", f"{self.url}/packages/{package_type.value}/{package_name}")
        return github.Package.Package(self._requester, headers, data, completed=True)
```

2025-04-03 16:07 UTC, Prateikx commented on tests/Package.py
> +        self.packages = self.user.get_packages("astral-sh")
**✨ AI Suggestion:** The `get_packages` method requires a package type argument, but it's called with a username. This will cause a TypeError.
```suggestion
        self.packages = self.user.get_packages(PackageType.CONTAINER)
```

2025-04-03 16:12 UTC, Prateikx commented on github/AuthenticatedUser.py
> +        assert isinstance(package_type , github.Package.PackageType), package_type
**✨ AI Suggestion:** The parameter `package_type` should be validated as a member of the `PackageType` enum, not just its type.
```suggestion
        if not isinstance(package_type, github.Package.PackageType):
            raise TypeError("package_type must be a member of github.Package.PackageType enum")
        assert isinstance(package_name, str), package_name
```

2025-04-03 16:12 UTC, Prateikx commented on github/NamedUser.py
> +    def get_package(self) -> Package:
**✨ AI Suggestion:** The `get_package` method lacks parameters for package type and name, making it unusable for retrieving specific packages.
```suggestion
    def get_package(self, package_type: github.Package.PackageType, package_name: str) -> Package:
        """
        :calls: `GET /users/{user}/packages/{package_type}/{package_name} <https://docs.github.com/en/rest/reference/packages>`_
        """
        if not isinstance(package_type, github.Package.PackageType):
            raise TypeError("package_type must be a member of github.Package.PackageType enum")
        assert isinstance(package_name, str), package_name
        headers, data = self._requester.requestJsonAndCheck("GET", f"{self.url}/packages/{package_type.value}/{package_name}")
        return github.Package.Package(self._requester, headers, data, completed=True)
```

2025-04-03 16:12 UTC, Prateikx commented on tests/Package.py
> +        self.packages = self.user.get_packages("astral-sh")
**✨ AI Suggestion:** The `get_packages` method requires a package type argument, but it's called with a username. This will lead to a TypeError.
```suggestion
        self.packages = self.user.get_packages(PackageType.CONTAINER)
```

2025-08-13 16:18 UTC, EnricoMi commented
Superseded by #3292.

2025-08-13 16:18 UTC, closed without merging