Fix typos
PyGithub/PyGithub pull request #3086
Opened 2024-12-02 14:02 UTC by kianmeng

Found via `codespell -S *.txt -L acces` and `typos --hidden --format brief`

2024-12-02 15:00 UTC, EnricoMi requested changes
LGTM, some test fixes required.

2024-12-02 15:00 UTC, EnricoMi commented on tests/Commit.py
> +        self.assertEqual(status.description, "Status successfully created by PyGithub")
this change requires changing `tests/ReplayData/Commit.testCreateStatusWithAllParameters.txt` as well.

2024-12-02 15:00 UTC, EnricoMi commented on tests/CommitStatus.py
> +        self.assertEqual(self.statuses[0].description, "Status successfully created by PyGithub")
this change requires changing `tests/ReplayData/CommitStatus.testAttributes.txt` as well.

2024-12-18 03:07 UTC, billnapier approved these changes

2024-12-18 08:21 UTC, EnricoMi approved these changes
LGTM!

2024-12-18 08:21 UTC, merged

2024-12-19 02:59 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: