Use `responses` instead of `httpretty` in tests
PyGithub/PyGithub pull request #3087
Opened 2024-12-06 11:14 UTC by majamassarini

I have created this PR since [httpretty](https://github.com/gabrielfalcao/HTTPretty/issues) seems to be no longer maintained.
Fedora is maintaining httpretty because it is needed in PyGithub.
I think it could be beneficial both for Fedora and PyGithub to move away from httpretty.

[responses project](https://github.com/getsentry/responses)

Thanks in advance.

2025-02-03 21:55 UTC, EnricoMi reviewed
This is awesome, thanks! Minor comments.

2025-02-03 21:55 UTC, EnricoMi commented on tests/Framework.py
>          return [status, response_headers, output]
Can you elaborate on why this is not needed anymore?

2025-02-03 21:55 UTC, EnricoMi commented on tests/ReplayData/GitRelease.testUploadAsset.txt
> -{"url":"https://api.github.com/repos/rickrickston123/RepoTest/releases/assets/22874904","id":22874904,"node_id":"MDEyOlJlbGVhc2VBc3NldDIyODc0OTA0","name":"archive.zip","label":"unit test artifact","u
Do you know why these test data specifically change?

2025-02-03 22:05 UTC, EnricoMi commented
Looks like there is an UTF8 encoding issue moving to `responses`:
https://github.com/PyGithub/PyGithub/pull/3087/checks#step:5:51

2025-02-05 14:32 UTC, majamassarini commented on tests/Framework.py
>          return [status, response_headers, output]
It has been a while since I wrote this code and I am not sure if I remember it correctly even because I have never really used `responses` but I found it quite nice to work with. I am just trying to get rid of managing `httpretty` in Fedora.
 
I think the reason is that I was finding more headers that somehow were *interfering with the response handling*, I have solved it in the other way around; checking just a subset of the headers [here](https://github.com/PyGithub/PyGithub/blob/429569c6f5f6c1bbfeadc129e0958506c892ac27/tests/Framework.py#L235-L238).

2025-02-12 11:38 UTC, majamassarini commented
@EnricoMi you catch it right, those line of code were needed. Now all the tests should pass.

2025-02-14 16:24 UTC, EnricoMi requested changes
This should fix lint errors.

2025-02-14 16:24 UTC, EnricoMi commented on tests/Retry.py
> +        self.assertEqual(repository.full_name, REPO_NAME)
```suggestion
        self.assertEqual(repository.full_name, REPO_NAME)

```

2025-02-14 16:24 UTC, EnricoMi commented on tests/Retry.py
> +import responses  # type: ignore
```suggestion
```

2025-02-14 16:24 UTC, EnricoMi commented on tests/Retry.py
>  import urllib3  # type: ignore
```suggestion
import responses
import urllib3
```

2025-02-14 16:24 UTC, EnricoMi commented on tests/ReplayData/Project.testProjectCardDelete.txt
> +
```suggestion
```

2025-02-14 16:24 UTC, EnricoMi commented on tests/ReplayData/Team.testRepoPermission.txt
> +
```suggestion
```

2025-02-14 16:24 UTC, EnricoMi commented on tests/Framework.py
>  from urllib3.util import Url  # type: ignore
```suggestion
import responses
from requests.structures import CaseInsensitiveDict
from urllib3.util import Url
```

2025-02-14 16:24 UTC, EnricoMi commented on tests/Connection.py
>  import pytest  # type: ignore
```suggestion
import pytest
import responses
```

2025-02-14 17:02 UTC, EnricoMi approved these changes
LGTM, thanks for migrating this!

2025-02-14 17:06 UTC, merged