Add enable and disable endpoints for Workflow
PyGithub/PyGithub pull request #3088
Opened 2024-12-07 03:13 UTC by nickrmcclorey

- add method to disable a workflow ([API reference](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#disable-a-workflow))
- add method to enable a workflow([API reference](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#enable-a-workflow))

2024-12-08 10:20 UTC, tituspijean commented
This will happily supersede #2356.

2024-12-17 23:05 UTC, billnapier approved these changes
this looks good to me

2025-02-03 22:37 UTC, EnricoMi requested changes

2025-02-03 22:37 UTC, EnricoMi commented on github/Workflow.py
> +        :calls: `PUT /repos/{owner}/{repo}/actions/workflows/{workflow_id}/disable <https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#get-a-workflow>`_
```suggestion
        :calls: `PUT /repos/{owner}/{repo}/actions/workflows/{workflow_id}/disable <https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#disable-a-workflow>`_
```

2025-02-03 22:38 UTC, EnricoMi approved these changes
LGTM!

2025-02-03 23:22 UTC, nickrmcclorey commented
> @nickrmcclorey please fix the type annotation issues.
> 
> https://github.com/PyGithub/PyGithub/actions/runs/13124240844/job/36617104328?pr=3088#step:6:12

@EnricoMi, thanks for taking a look and correcting those docs links. I just added the type annotations.

2025-02-14 19:43 UTC, merged